### ISSUE TITLE
Error connecting via SquirrelSQL

### ISSUE THREAD

**Issue by bryanross** [mmolimar/ksql-jdbc-driver#15]
I cloned the latest repository, built a fat jar and tried to connect with SquirrelSQL 3.9.1.  I receive the error below.  Any clues?  I have confirmed that I can connect to the KSQL engine and run queries using the Confluent CLI.

Unexpected Error occurred attempting to open an SQL connection.
class org.apache.kafka.common.config.ConfigException: Invalid value 

org.apache.kafka.streams.errors.LogAndFailExceptionHandler for configuration 
default.deserialization.exception.handler: Class org.apache.kafka.streams.errors.LogAndFailExceptionHandler could not be found.

**Comment by mmolimar** [comment]
Could you try adding to the classpath the dependency ``org.apache.kafka:kafka-streams``?
Which KSQL version are you using? And the connection URL?

**Comment by bryanross** [comment]
I added the kafka-streams-2.3.0.jar to the classpath but received the same error.  I also verified the class LogAndFailExceptionHandler existed in the jar.  I'm using KSQL 5.2.2.  My URL is very basic:  jdbc:ksql://127.0.0.1:8088.  I verified the port number because I can connect to the KSQL server using that port and running the query.

This is interesting....I just tried it with JetBrains DataGrip and got further.  I could connect but not run any SQL statement because of the KSQLStatement throwing "Unsupported" exceptions and DataGrip will call setFetchSize to limit results to 500 by default.  I did a quick test by changing the source to not throw the error on setFetchSize and then the next method gave me an error: getType().  Perhaps the lack of full JDBC support is causing SquirrelSQL and DataGrip issues.

What are your thoughts?  Do you have this working with SquirrelSQL?  If so, what version?

**Comment by d-thomson** [comment]
I had success using dbeaver if you want to give that client a try

**Comment by bryanross** [comment]
DBeaver partially works where I can get integer values but not string values.  String values show "DBException: SQL Error: Feature not supported".  This leads me back to these tools expecting more of the JDBC spec to be supported.

Thank you both for the help.  The promise of the JDBC driver is exciting.  I was looking to see what I could do with this and Tableau but it may be a bit premature.
