### ISSUE TITLE
is any files available？function list .etc?

### ISSUE THREAD

**Issue by gbasehd** [mmolimar/ksql-jdbc-driver#2]
Hi, i‘m interested in this project and want to know more about it，so would you please offer me some doucuments, such as supported version, dev plan...，anything about this wonderful project. thanks.

**Comment by mmolimar** [comment]
Hello,

I think you have all info you need in the readme file...
Right now, it is tested in ksql v0.1 but in a near future I want to upgrade to a new version and add new features.

Thanks for your comment.
