### ISSUE TITLE
Driver Failed to Connect due to Exception casting issue

### ISSUE THREAD

**Issue by avatarsol** [mmolimar/ksql-jdbc-driver#23]
Trying to do Test Connection using this driver from Jasper Server to KSQLDB (both working separately).

27-May-2020 10:51:07.225 SEVERE [http-nio-8080-exec-6] org.glassfish.jersey.server.ServerRuntime$Responder.mapException An exception has been thrown from an exception mapper class com.jaspersoft.jasperserver.jaxrs.common.GenericRemoteExceptionMapper.
	java.lang.ClassCastException: java.lang.NoClassDefFoundError cannot be cast to java.lang.Exception
		at com.jaspersoft.jasperserver.jaxrs.common.GenericRemoteExceptionMapper.toResponse(GenericRemoteExceptionMapper.java:66)
		at com.jaspersoft.jasperserver.jaxrs.common.GenericRemoteExceptionMapper.toResponse(GenericRemoteExceptionMapper.java:45)

**Comment by mmolimar** [comment]
Do you have the fat jar or all required deps properly set in the classpath?

**Comment by avatarsol** [comment]
Thanks for your reply

Regarding Jasper Server, I try to register both thin and fat driver in the way all other JDBC drivers we use (Postgres, MySQL, Snowflake, using Jasper DataSource web interface) and in both cases the mentioned error appears (happens for both Jasper Server version 7.1 and 7.5, both commercial and community version). 

As mentioned in another issue, simple Java console app I tried also is not able to use driver successfully, as tested on Ubuntu 16.04 (OpenJDK Runtime Environment AdoptOpenJDK, build 11.0.3+7) and Mac OS (OpenJDK Runtime Environment, build 13.0.1+9), simple test code and cmd line attached below (also fails for both thin and fat driver jar), for working ksqldb 
(docker ps:
f4e52853fcd4        confluentinc/ksqldb-server:0.9.0         "/usr/bin/docker/run"    27 hours ago        Up 27 hours         0.0.0.0:8088->8088/tcp )

I appreciate your work, but would appreciate working reference sample, that can probably help many users, as simple integration doesn't seem to work... Thanks

// KSQLSample.java
import java.sql.*;
public class KSQLSample {
   static final String JDBC_DRIVER = "com.github.mmolimar.ksql.jdbc.KsqlDriver";
   static final String DB_URL = "jdbc:ksql://localhost:8088";  // ksql db demo here works
   public static void main(String[] args) {
     Connection conn = null;
     Statement stmt = null;
     try {
          Class.forName(JDBC_DRIVER );
          conn = DriverManager.getConnection(DB_URL);  //error here
     } catch(SQLException se) {
          se.printStackTrace();
     } catch(Exception e) {
          e.printStackTrace();
     }
}

java -cp ".:./seed-project-assembly-1.2.0.jar" KSQLSample
java.sql.SQLException: No suitable driver found for jdbc:ksql://localhost:8088
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at KSQLSample.main(KSQLSample.java:18)

**Comment by mmolimar** [comment]
Have you tried in Squirrel SQL and change the JDK to Oracle JDK8?

**Comment by avatarsol** [comment]
Thanks, I tried Oracle Java as suggested:
Java(TM) SE Runtime Environment (build 14.0.1+7) 
on another Ubuntu (18.04) box got the same error:
java.sql.SQLException: No suitable driver found for jdbc:ksql://localhost:8088
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at KSQLSample.main(KSQLSample.java:11)

I also tried Squirrel-SQL, which registers Driver OK (same as Jasper, OpenJDK and Oracle JDK), and displays STREAM, TABLE and UDT node, but displays error messages on access (double-click any of these) as below:
Driver class com.github.mmolimar.ksql.jdbc.KsqlDriver successfully registered for driver definition: ksql
Please try out the Tools popup by hitting ctrl+t in the SQL Editor. Do it three times to stop this message.
Error: STREAM: io.confluent.ksql.rest.client.KsqlRestClientException: Error issuing POST to KSQL server. path:/ksql

KSQLDB that I try to access is just a basic sample setup from: https://ksqldb.io/quickstart.html that works OK from prompt.

More help would be appreciated.

**Comment by avatarsol** [comment]
Also, not sure if this might be related, but while I was able to build driver jars in OpenJDK 13 on Mac, the same build fails with Oracle JDK 14 on Ubuntu 18.04, with errors as below. It would be helpful if you can post a binary zip (with compiled version of the jar that works for you in Squirrel-SQL)?! Thanks

[info] Resolved  dependencies
[warn]  
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.openjfx:javafx.base:11.0.0-SNAPSHOT
[error]   not found: /home/miomir/.ivy2/local/org.openjfx/javafx.base/11.0.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/openjfx/javafx.base/11.0.0-SNAPSHOT/javafx.base-11.0.0-SNAPSHOT.pom

**Comment by mmolimar** [comment]
The driver is tested with JDK8 and, on the other hand, each version of the driver is linked to a KSQL version, do they match?

**Comment by avatarsol** [comment]
I tried OracleJDK 8 (Java(TM) SE Runtime Environment (build 1.8.0_251-b08)

**Comment by avatarsol** [comment]
I was able to build driver with suggested Oracle JDK8 version (while build fails with Oracle JDK14). However when running simple Java code above (in either Oracle JDK8, 14 or OpenJDK11 and 13), trying to connect to SQLDB with new built driver, I still see the same error java.sql.SQLException: No suitable driver found at DriverManager.java:689), as with old driver (built with OpenJDK 13).

I do not quite understand your suggestion to match KSQL versions. What I see in driver built.sbt is 
val ksqlVersion = "5.4.0", but no ksqldb version.
There is no matching settings in the reference confluent docker compose file, only:
image: confluentinc/ksqldb-server:0.9.0

Some more help would be appreciated.
