### ISSUE TITLE
Error: Could not initialize class io.confluent.ksql.config.KsqlConfigResolver

### ISSUE THREAD

**Issue by avatarsol** [mmolimar/ksql-jdbc-driver#26]
Hi

I built KSQLDB driver and can connect now to my datasource from Java, and also in SQuirrelSQL (thanks for input). However, the connection to the same datasource and using the same driver fails from some other tools that use JDBC, such as Jasper Reports community server.

The error is: 

Could not initialize class io.confluent.ksql.config.KsqlConfigResolver. 
at java.lang.Thread.run(Thread.java:748)
08-Jun-2020 17:54:56.804 SEVERE [http-nio-8080-exec-9] org.glassfish.jersey.server.ServerRuntime$Responder.mapException An exception was not mapped due to exception mapper failure. The HTTP 500 response will be returned.

Is there any dependencies I could include in driver via build process or any other suggestion you might have?!

Thanks

**Comment by mmolimar** [comment]
Hi.
Is the fat jar included in the classpath? Which version of KSQL are you using? It should match with the one the driver uses.

**Comment by avatarsol** [comment]
Hello, yes, fat driver is built fine and it works with Docker demo simple sample.
I am trying now to use the same Java (to be extended for real functionality) code now without Docker, using Confluent Community Platform 5.5.0 (installation from here: https://docs.confluent.io/current/installation/installing_cp/zip-tar.html#prod-kafka-cli-install), not sure how to check that they match the driver version. Installation and ksql prompt work
ksql> version
Version: 5.5.0. 
The described error is with Reporting tool GUI trying to connect with Driver. Java sample gives again the error:
java.sql.SQLException: No suitable driver found for jdbc:ksql://localhost:8088
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at KSQLSample.main(KSQLSample.java:19)
Help would be appreciated.

**Comment by avatarsol** [comment]
I was able to resolve Java connectivity by configuring installed Confluent suite. I will try to pursue issue with the Reporting system by vendor. Closing issue. Thanks

**Comment by mmolimar** [comment]
Great! ;-)
