### ISSUE TITLE
Cannot connect to this URL 192.168.30.190. Error message: Error issuing GET to KSQL server. path:/info

### ISSUE THREAD

**Issue by GevyYuan** [mmolimar/ksql-jdbc-driver#31]
I have deployed confluent-5.2.3, and confirmed that ksql has been started and port 8088 has been listened, but there is an error in linking through JDBC

The code is as follows:
Class.forName("com.github.mmolimar.ksql.jdbc.KsqlDriver");
        String url="jdbc:ksql://192.168.30.190:8088";
        KsqlDriver kd= new KsqlDriver();

        System.out.println(kd.acceptsURL(url));

        KsqlConnection con = kd.buildConnection(KsqlDriver.parseUrl(url), null);

        con.validate();

        Statement statement = con.createStatement();

        ResultSet rs = statement.executeQuery("select ROWTIME,ROWKEY from USERS");

        while(rs.next()){

            System.out.println(rs.getInt(0)+" ： "+rs.getString(1));

        }
The error is as follows:
Exception in thread "main" java.sql.SQLException: Cannot connect to this URL 192.168.30.190. Error message: Error issuing GET to KSQL server. path:/info
	at com.github.mmolimar.ksql.jdbc.Exceptions$.wrapException(Exceptions.scala:84)
	at com.github.mmolimar.ksql.jdbc.KsqlConnection.validate(KsqlConnection.scala:184)
	at ksqltest.main(ksqltest.java:20)

**Comment by mmolimar** [comment]
Hi!
Which version are you using?
The latest version of the driver supports Confluent 5.4.0. This might be the use so you might need to use a previous version.

**Comment by GevyYuan** [comment]
> Hi!
> Which version are you using?
> The latest version of the driver supports Confluent 5.4.0. This might be the use so you might need to use a previous version.

But I tried confluent-5.4.0 and this problem was solved. Thanks
