### ISSUE TITLE
readme build instructions seem incorrect? 

### ISSUE THREAD

**Issue by joefromct** [mmolimar/ksql-jdbc-driver#6]
From this line:

`git clone https://github.com/confluentinc/ksql.git && cd ksql && git v4.1.0-rc3`

I'm getting an error on the this part:

```` 
➜  ksql git:(master) git v4.1.0-rc3
git: 'v4.1.0-rc3' is not a git command. See 'git --help'.
➜  ksql git:(master)                       
````

That has to be a typo right? 

I'm just trying to get a jar file for other applications to connect to ksql engines.... is anything in maven central where i can just pull a nicely packaged *.jar?  

Thanks in advance,

**Comment by mmolimar** [comment]
Yes, you're right!
Fixed :-)
