### ISSUE TITLE
works with ksql, but ksql-jdbc-driver says `Error issuing GET to KSQL server`

### ISSUE THREAD

**Issue by joefromct** [mmolimar/ksql-jdbc-driver#8]
Hi,

After resolving #7 , it appears I may still have something missing. 

I have a small kafka test server running ksql-engine on the default port; and can connect like so from ksql on a command line; I can list topics, etc. everything looks good.

```` bash
➜  confluent-5.0.0 ./bin/ksql http://my-kafka-server:8088
                  ...clip...
                  =  Streaming SQL Engine for Apache Kafka® =
                  ===========================================

Copyright 2017-2018 Confluent Inc.
CLI v5.0.0, Server v5.0.0 located at http://my-kafka-server:8088
Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!
ksql> 
````

However, when connecting through ksql I'm getting the following error message with the equivelent (?) connection url such as `jdbc:ksql://my-kafka-server:8088`: 

````
Your server is accepting socket connections on my-kafka-server:8088.
Cannot connect to this URL my-kafka-server. Error message: Error issuing GET to KSQL server
 ````
This seems like a generic message, because even if i change my connection url to `jdbc:ksql://github.com:443` I get the same error...

Apologies if I've overlooked something, and thanks again for your help.

**Comment by dthomson30** [comment]
This is where I got stuck too - KSQL server listening, accepting connections, able to access the UI from a browser as well as the CLI. Just getting the generic "Error issuing GET to KSQL server". Were you able to solve this?

**Comment by dthomson30** [comment]
Is the http getting trimmed from the string somewhere? wondering if this this the reason

![http](https://user-images.githubusercontent.com/46693107/51941741-5610ca00-23e3-11e9-99fa-db9bfd33a852.png)

**Comment by mmolimar** [comment]
Hi.
I'm working right now in a new version compatible with latest release of KSQL. It'll be available very soon and I think you shouldn't get this kind of issues with this new driver version.

**Comment by mmolimar** [comment]
Can you try with the new version?

**Comment by joefromct** [comment]
Yup, works good. 

sorry for the delayed response.  I'll close this now.
